### ISSUE TITLE
Download History is Not Recorded

### ISSUE THREAD

**Issue by digitalam025** [doublethreedigital/sc-digital-products#102]
### Bug Description

Hi! As the title suggests, with each visit to a unique download URL, download histories are not recorded.

I suggest that the error comes from:
`\DoubleThreeDigital\DigitalProducts\Http\Controllers\DownloadController.php`
```php
$order->updateLineItem($item['id'], [
                    'metadata' => array_merge([
                        'download_history' => array_merge(
                            [
                                [
                                    'timestamp'  => now()->timestamp,
                                    'ip_address' => $request->ip(),
                                ],
                            ],
                            isset($item['metadata']['download_history']) ? $item['metadata']['download_history'] : [],
                        ),
                    ], Arr::get($item, 'metadata', [])),
                ]);
```

From what I understand from these lines of code is that a new array of `download_history` is created with a new timestamp and ip address, but it gets overwritten by the original array afterwards.

Specifically the line `Arr::get($item, 'metadata', [])` where its initial value is always an empty array.

### Steps to reproduce

**To Replicate the Bug**
1. Install simple-commerce Starter Kit.
2. Install this package and added the 'digital_download_ready' notification.
3. Create a digital product.
4. Create an order with the digital product. (Tried mixing and matching products with non-digital ones too)
5. Click on the link that was sent via email. / Copy the `download_url` from the [order_id].md file to the browser.

**Steps to Reach This Conclusion**
1. Dumping and dying (`dd()`) the array shown in the description above.
2. Testing Step 1 with and without `Arr::get($item, 'metadata', [])`

### Environment

Statamic 3.2.24 Solo
Laravel 8.73.2
PHP 8.0.9
doublethreedigital/sc-digital-products 2.2.2
doublethreedigital/simple-commerce 2.3.53

**Comment by duncanmcclean** [comment]
Thanks again for opening an issue!

Sorry for the wait to get this fixed - I've been really busy over the last few days at work and not had chance to look into this. I'm not usually this slow 😅 

When I've got some time, I'll take a look at the issue and get it fixed. In the meantime, if you figure it out and know how to fix it, feel free to open a pull request.
