### ISSUE TITLE
support omnipay

### ISSUE THREAD

**Issue by mbnoimi** [doublethreedigital/sc-digital-products#117]
### What would you like to see added?

[Omnipay](https://github.com/thephpleague/omnipay) multi-gateway payment processing library

### Is there a workaround you can use in the meantime?

I don't know

### Priority wise - where's this feature for you?

Will need it in the next few weeks

**Comment by duncanmcclean** [comment]
Simple Commerce is not going to support omnipay, it would be a major refactor and we already have a working gateway system.

If there's a gateway that's missing, you can [implement it yourself](https://simple-commerce.duncanmcclean.com/extending/custom-gateways).
