### ISSUE TITLE
Limit number of downloads

### ISSUE THREAD

**Issue by barchard** [doublethreedigital/sc-digital-products#71]
Limit the number of times an asset can be downloaded.

**Comment by duncanmcclean** [comment]
Would this be on a per product basis or would this be on a global/whole site basis?

**Comment by barchard** [comment]
Per product.

**Comment by duncanmcclean** [comment]
Cool, thanks!

**Comment by duncanmcclean** [comment]
I've implemented this, there will be a setting on a per product basis (see screenshot). Released in [v2.0.3](https://github.com/doublethreedigital/sc-digital-products/releases/tag/v2.0.3).

![image](https://user-images.githubusercontent.com/19637309/108782046-c3f83300-7562-11eb-97ac-eba1f0d414d6.png)
