### ISSUE TITLE
Unique ID for downloads

### ISSUE THREAD

**Issue by barchard** [doublethreedigital/sc-digital-products#72]
A unique and obstructed ID should be supplied for a digital download. This should not be something someone can guess so products can't be downloaded without purchasing.

**Comment by duncanmcclean** [comment]
Digital Products generates a signed URL as the download link which would need a valid license key, paid order and would need the correct token to access, is that not what you mean?

Here's an example by the way:

```
http://sc-dev.test/!/sc-digital-products/download/3eef0965-aaba-4007-95c2-8128ce4b0d44/a50a22d3-432f-4b6c-85db-48ea7ba92036?license_key=COt2IXuPqP6VTg3cfXmqQmP0&signature=9fafcd61a4242368f4d31baf3c9a2f3449a0ccd1f808dff6c59eef861ba81c14
```
