### ISSUE TITLE
Retrieve lost license support

### ISSUE THREAD

**Issue by barchard** [doublethreedigital/sc-digital-products#74]
### Description

There are two implementations/ideas to support this:

1. Clients/Customers have a Statamic log in where they are able to view previous orders or
2. Simple form where the user fills in their email address and *all* orders found having used that email are re-sent to that email address. (order summary can be combined into 1 email)

**Comment by barchard** [comment]
I thought about this some more, an even simpler 1.0 would be to add:

1. API support so it can be done via AJAX
2. A mailable template so it can send all licenses/links via email

A version down the road can add:

1. A Template/Blueprint 
2. User logins

**Comment by duncanmcclean** [comment]
Hey Gregory, sorry for taking so long to respond to this but here's how I'd approach this issue:

1. Switch the 'customer driver' (found in your `simple-commerce.php` config file) to `\DoubleThreeDigital\SimpleCommerce\Customers\UserCustomer::class` (it'll mean your customers are powered by Statamic's user system, not Customer entries)
2. Create your own login/register pages during checkout so people can create their accounts/login etc
3. Attach the user/customer to the order during checkout `<input type="hidden" name="customer" value="{{ user }}{{ id }}{{ /user }}">`
4. Then create a template for the user's account where they can view their orders... here's [an example](https://github.com/doublethreedigital/sc-customer-login-demo/blob/main/resources/views/account.antlers.html) of what I mean.

Bearing in mind with the above instructions you'll need to be on Statamic Pro (so you can have multiple users) and you'll need to be using Simple Commerce v2.3.14 or higher.

Hopefully that helps! I'm going to close this issue now. If you have any problems with the custom customer driver stuff, please [create an issue](https://github.com/doublethreedigital/simple-commerce/issues/new/choose) on the main SC repo. Thanks!
