### ISSUE TITLE
Make notification class configurable

### ISSUE THREAD

**Issue by ryanmitchell** [doublethreedigital/sc-digital-products#92]
### What would you like to see added?

I'd like to be able to override the notification class for the email that is triggered on purchase, so we can override the logic for the provider we want to use.

### Is there a workaround you can use in the meantime?

I don't think so - we have to use laravel notifications as its the default.

### Priority wise - where's this feature for you?

I'm going to need it at some point in the future but it's not major right now.

**Comment by ryanmitchell** [comment]
Thank you!

**Comment by duncanmcclean** [comment]
No worries! I've released it in [v2.2.0](https://github.com/doublethreedigital/sc-digital-products/releases/tag/v2.2.0)
